services:
    rstudio:
        image: rstudio_jp:1.0.0
        container_name: rmarkdown
        build: 
            context: _rstudio
        volumes: 
            - .:/home/rstudio/rmarkdown
        ports:
            - "8787:8787"
        env_file:
            - ./_rstudio/rstudio.env
        environment:
            - DISABLE_AUTH=true
        tty: true